accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', views.signup.as_view(), name='signup'),
    path('accounts/verify/', views.verifyCodeView.as_view(), name='verify_code'),
    path('accounts/login/', views.loginView.as_view(), name='login'),
    path('accounts/logout/', views.logoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# if settings.DEBUG:  # Only used during development
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('checking_order/', views.HomeAPIView.as_view(), name='checking_order')
]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }} message">{{ message }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:home' %}">Food Place</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <a class="nav-link" href="#">{{ user.name }}</a>
            <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
          {% else %}
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>